version: '3.9'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: pgvector
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: aidb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      PGPASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


#  docker compose up -d

#  docker compose down           остановить и удалить контейнеры
#  docker compose ps             посмотреть запущенные контейнеры
#  docker compose logs -f        логи в реальном времени
#  docker compose restart        перезапуск
