spring:
  application:
    name: Helper-Spring-AI
  ai:
    mistralai:
      chat:
        option:
          model: "mistral-small-latest"
      api-key: ${MY-APP-KEY}

  datasource:
    url: jdbc:postgresql://localhost:5435/aidb
    username: user
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

app:
  maxMessages: 10
  expansionTemp: 0.1
  expansionTopP: 0.2